<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MJ03JXF1" name="test.java.com.lol.tests.OM63_AgencyOP_at_zerocost_Saleofproduct_nightly_generationofOMwithcommission_line" tests="1" failures="1" timestamp="6 Jul 2017 13:44:37 GMT" time="128.801" errors="0">
  <testcase name="t220208_P4310_Purchaseordercreation_with_valid_freight_handling_code" time="128.801" classname="test.java.com.lol.tests.OM63_AgencyOP_at_zerocost_Saleofproduct_nightly_generationofOMwithcommission_line">
    <failure type="java.lang.AssertionError" message="Object having Xpath as .//*[@id=&#039;hc_Close&#039;] not found. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Object having Xpath as .//*[@id='hc_Close'] not found. expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at test.java.com.lol.utils.Common.getObjectByXpath(Common.java:578)
	at test.java.com.lol.tests.OM63_AgencyOP_at_zerocost_Saleofproduct_nightly_generationofOMwithcommission_line.t220208_P4310_Purchaseordercreation_with_valid_freight_handling_code(OM63_AgencyOP_at_zerocost_Saleofproduct_nightly_generationofOMwithcommission_line.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- t220208_P4310_Purchaseordercreation_with_valid_freight_handling_code -->
</testsuite> <!-- test.java.com.lol.tests.OM63_AgencyOP_at_zerocost_Saleofproduct_nightly_generationofOMwithcommission_line -->
